// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221011033616_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CompetenceAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(852),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(853),
                            ModifiedBy = "",
                            Name = "Fachkompetenz",
                            Weighting = 0.29999999999999999
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(855),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(857),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen",
                            Weighting = 0.10000000000000001
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(858),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(860),
                            ModifiedBy = "",
                            Name = "Allgemeinbildung",
                            Weighting = 0.20000000000000001
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceAreaEducationType", b =>
                {
                    b.Property<int>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<int>("EducationTypeId")
                        .HasColumnType("int");

                    b.HasKey("CompetenceAreaId", "EducationTypeId");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreaEducationTypes");

                    b.HasData(
                        new
                        {
                            CompetenceAreaId = 1,
                            EducationTypeId = 1
                        },
                        new
                        {
                            CompetenceAreaId = 2,
                            EducationTypeId = 1
                        },
                        new
                        {
                            CompetenceAreaId = 3,
                            EducationTypeId = 1
                        },
                        new
                        {
                            CompetenceAreaId = 2,
                            EducationTypeId = 2
                        },
                        new
                        {
                            CompetenceAreaId = 3,
                            EducationTypeId = 2
                        },
                        new
                        {
                            CompetenceAreaId = 1,
                            EducationTypeId = 3
                        },
                        new
                        {
                            CompetenceAreaId = 2,
                            EducationTypeId = 3
                        },
                        new
                        {
                            CompetenceAreaId = 3,
                            EducationTypeId = 3
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeGoalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("EducationTypeGoalId");

                    b.ToTable("EducationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(806),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(832),
                            ModifiedBy = "",
                            Name = "EFZ"
                        },
                        new
                        {
                            Id = 2,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(835),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(836),
                            ModifiedBy = "",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(838),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 11, 5, 36, 15, 937, DateTimeKind.Local).AddTicks(839),
                            ModifiedBy = "",
                            Name = "IMS"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3db2dacb-3b22-47a9-8684-4917c89c7abb",
                            ConcurrencyStamp = "9790fab9-2bd9-49a3-9d18-f6d4c2e1c180",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b3d962e5-7c90-4868-9327-989c080701b2",
                            ConcurrencyStamp = "878d4671-1c4e-4eed-92a4-e6ae7d93f338",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceAreaEducationType", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany()
                        .HasForeignKey("CompetenceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany()
                        .HasForeignKey("EducationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetenceArea");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("EducationTypes")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.EducationTypeGoal", "EducationTypeGoal")
                        .WithMany("EducationTypes")
                        .HasForeignKey("EducationTypeGoalId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("EducationTypeGoal");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeTrackerAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("EducationTypes");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Navigation("EducationTypes");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
