// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221024210745_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5659),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5662),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5664),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5665),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5667),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5668),
                            ModifiedBy = "",
                            Name = "Allgemeinbildung"
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5669),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5671),
                            ModifiedBy = "",
                            Name = "ÜK"
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5672),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5673),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 6,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5675),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5676),
                            ModifiedBy = "",
                            Name = "Erweiterte Allgemeinbildung"
                        },
                        new
                        {
                            Id = 7,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5678),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5679),
                            ModifiedBy = "",
                            Name = "ÜK"
                        },
                        new
                        {
                            Id = 8,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5680),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5682),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 9,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5683),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5684),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 10,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5686),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5687),
                            ModifiedBy = "",
                            Name = "Erweiterte Allgemeinbildung"
                        },
                        new
                        {
                            Id = 11,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5689),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5690),
                            ModifiedBy = "",
                            Name = "ÜK"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5504),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5540),
                            ModifiedBy = "",
                            Name = "EFZ"
                        },
                        new
                        {
                            Id = 2,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5543),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5545),
                            ModifiedBy = "",
                            Name = "BM"
                        },
                        new
                        {
                            Id = 3,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5546),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 24, 23, 7, 44, 810, DateTimeKind.Local).AddTicks(5548),
                            ModifiedBy = "",
                            Name = "MS"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("CompetenceAreas")
                        .HasForeignKey("EducationTypeId");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("EducationTypeId");

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("EducationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Navigation("CompetenceAreas");

                    b.Navigation("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
