// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220817123249_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6214),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6216),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6219),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6221),
                            ModifiedBy = "",
                            Name = "Erweiterte Kompetenzen"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6223),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6225),
                            ModifiedBy = "",
                            Name = "Allgemeinbildung"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeGoalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeGoalId");

                    b.ToTable("EducationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6182),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6185),
                            ModifiedBy = "",
                            Name = "Eidgenössisches Berufsattest (EBA)"
                        },
                        new
                        {
                            Id = 2,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6188),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6190),
                            ModifiedBy = "",
                            Name = "Eidgenössisches Fachzertifikat (EFZ)"
                        },
                        new
                        {
                            Id = 3,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6193),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6195),
                            ModifiedBy = "",
                            Name = "Berufsmatura (BMS)"
                        },
                        new
                        {
                            Id = 4,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6197),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6199),
                            ModifiedBy = "",
                            Name = "IMS"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1298),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1310),
                            ModifiedBy = "",
                            Name = "INF 226B",
                            ShowOnDashboard = true,
                            TeacherId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1314),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1316),
                            ModifiedBy = "",
                            Name = "Mathematik",
                            ShowOnDashboard = false,
                            TeacherId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1319),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 567, DateTimeKind.Local).AddTicks(1321),
                            ModifiedBy = "",
                            Name = "Sprache und Kommunikation",
                            ShowOnDashboard = false,
                            TeacherId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7725),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7738),
                            ModifiedBy = "",
                            Name = "Roland Bucher"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7741),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7743),
                            ModifiedBy = "",
                            Name = "Fritz Kempf"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7745),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(7747),
                            ModifiedBy = "",
                            Name = "Marcel Schorno"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6004),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6049),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Evan"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6053),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6055),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Apisana"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6057),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 17, 14, 32, 49, 566, DateTimeKind.Local).AddTicks(6059),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Robert"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("CompetenceAreas")
                        .HasForeignKey("EducationTypeId");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationTypeGoal", "EducationTypeGoal")
                        .WithMany("EducationTypes")
                        .HasForeignKey("EducationTypeGoalId");

                    b.Navigation("EducationTypeGoal");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId");

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Navigation("CompetenceAreas");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Navigation("EducationTypes");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
