// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220816134050_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreas");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeGoalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeGoalId");

                    b.ToTable("EducationTypes");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2842),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2918),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Evan"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2921),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2923),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Apisana"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2925),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 8, 16, 15, 40, 50, 744, DateTimeKind.Local).AddTicks(2926),
                            ModifiedBy = "",
                            Password = "1234qweR",
                            Username = "Robert"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("CompetenceAreas")
                        .HasForeignKey("EducationTypeId");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationTypeGoal", "EducationTypeGoal")
                        .WithMany("EducationTypes")
                        .HasForeignKey("EducationTypeGoalId");

                    b.Navigation("EducationTypeGoal");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId");

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Navigation("CompetenceAreas");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Navigation("EducationTypes");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
