// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230108225101_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3861),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3863),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3865),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3866),
                            ModifiedBy = "",
                            Name = "Erweiterte Kompetenzen"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3868),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3869),
                            ModifiedBy = "",
                            Name = "Allgemeinbildung"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeGoalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeGoalId");

                    b.ToTable("EducationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3659),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3702),
                            ModifiedBy = "",
                            Name = "Eidgenössisches Berufsattest (EBA)"
                        },
                        new
                        {
                            Id = 2,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3707),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3708),
                            ModifiedBy = "",
                            Name = "Eidgenössisches Fachzertifikat (EFZ)"
                        },
                        new
                        {
                            Id = 3,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3736),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3737),
                            ModifiedBy = "",
                            Name = "Berufsmatura (BMS)"
                        },
                        new
                        {
                            Id = 4,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3738),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(3739),
                            ModifiedBy = "",
                            Name = "IMS"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7509),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7521),
                            ModifiedBy = "",
                            Name = "INF 226B",
                            ShowOnDashboard = true,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7526),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7527),
                            ModifiedBy = "",
                            Name = "Mathematik",
                            ShowOnDashboard = false,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7529),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(7530),
                            ModifiedBy = "",
                            Name = "Sprache und Kommunikation",
                            ShowOnDashboard = false,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4904),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4915),
                            ModifiedBy = "",
                            Name = "Roland Bucher"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4918),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4919),
                            ModifiedBy = "",
                            Name = "Fritz Kempf"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4921),
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 1, 8, 23, 51, 1, 616, DateTimeKind.Local).AddTicks(4922),
                            ModifiedBy = "",
                            Name = "Marcel Schorno"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("CompetenceAreas")
                        .HasForeignKey("EducationTypeId");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationTypeGoal", "EducationTypeGoal")
                        .WithMany("EducationTypes")
                        .HasForeignKey("EducationTypeGoalId");

                    b.Navigation("EducationTypeGoal");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId");

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Navigation("CompetenceAreas");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Navigation("EducationTypes");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
