// <auto-generated />
using System;
using GradeTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeTrackerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("CompetenceAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3588),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3591),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3594),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3596),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3599),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3601),
                            ModifiedBy = "",
                            Name = "Allgemeinbildung"
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3604),
                            EducationTypeId = 1,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3606),
                            ModifiedBy = "",
                            Name = "ÜK"
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3609),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3611),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 6,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3614),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3616),
                            ModifiedBy = "",
                            Name = "Erweiterte Allgemeinbildung"
                        },
                        new
                        {
                            Id = 7,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3618),
                            EducationTypeId = 2,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3620),
                            ModifiedBy = "",
                            Name = "ÜK"
                        },
                        new
                        {
                            Id = 8,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3623),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3625),
                            ModifiedBy = "",
                            Name = "Fachkompetenzen"
                        },
                        new
                        {
                            Id = 9,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3628),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3630),
                            ModifiedBy = "",
                            Name = "Erweiterte Grundkompetenzen"
                        },
                        new
                        {
                            Id = 10,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3632),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3635),
                            ModifiedBy = "",
                            Name = "Erweiterte Allgemeinbildung"
                        },
                        new
                        {
                            Id = 11,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3637),
                            EducationTypeId = 3,
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3639),
                            ModifiedBy = "",
                            Name = "ÜK"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Calculation")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3506),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3552),
                            ModifiedBy = "",
                            Name = "EFZ"
                        },
                        new
                        {
                            Id = 2,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3558),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3560),
                            ModifiedBy = "",
                            Name = "BM"
                        },
                        new
                        {
                            Id = 3,
                            Calculation = 1.0,
                            CreateBy = "",
                            CreatedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3563),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 10, 21, 15, 24, 52, 893, DateTimeKind.Local).AddTicks(3565),
                            ModifiedBy = "",
                            Name = "MS"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AverageDesiredMark")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weighting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageDesiredMark")
                        .HasColumnType("float");

                    b.Property<int?>("CompetenceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceAreaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "4fec0ca6-24a3-4815-8b47-b75e56d645ff",
                            ConcurrencyStamp = "a87878be-10fe-42f5-9d3f-ee401cf02cbc",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "a5fd9f22-4f33-4981-964b-574f7c2f159c",
                            ConcurrencyStamp = "5f5dd8f4-c3f1-460c-8ccf-26ebabefae6c",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("CompetenceAreas")
                        .HasForeignKey("EducationTypeId");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationTypeGoal", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.EducationType", "EducationType")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("EducationTypeId");

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("EducationTypeGoals")
                        .HasForeignKey("UserId");

                    b.Navigation("EducationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Mark", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.Module", "Module")
                        .WithMany("Marks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.HasOne("GradeTrackerAPI.Entities.CompetenceArea", "CompetenceArea")
                        .WithMany("Modules")
                        .HasForeignKey("CompetenceAreaId");

                    b.HasOne("GradeTrackerAPI.Entities.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeTrackerAPI.Entities.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("CompetenceArea");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.CompetenceArea", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.EducationType", b =>
                {
                    b.Navigation("CompetenceAreas");

                    b.Navigation("EducationTypeGoals");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Module", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.Teacher", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GradeTrackerAPI.Entities.User", b =>
                {
                    b.Navigation("EducationTypeGoals");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
